<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <Content Remove="wwwroot\js\bundle.d.ts.map" />
    <Content Remove="wwwroot\js\bundle.js" />
    <Content Remove="wwwroot\js\bundle.js.map" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Remove="wwwroot\js\bundle.d.ts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.8.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="wwwroot\js\app.ts" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\js\bundle.js" />
    <None Include="wwwroot\js\bundle.js.map" />
    <None Include="wwwroot\js\bundle.d.ts" />
    <None Include="wwwroot\js\bundle.d.ts.map" />
  </ItemGroup>

</Project>
